apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs-api-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      containers:
      - name: benlink-nodejs-api
        image: benlink/nodejs-api:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 1536Mi
            cpu: 55m
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
  labels:
    app: nodejs-api
spec:
  selector:
    app: nodejs-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
